pipeline {
agent {
    node {
                     label "172.31.30.118"
    }
}

tools {
    git "my-git"
}
    
    stages {
        
        stage('Build Docker image') {
            
            steps {

                dir ('/home/ec2-user/workspace/assign-1/simple') { 
                // Build the Docker image
                sh 'sudo docker build -t test_image:1.0 .'
            }
        }
        } 
        stage('Docker Login') {
           
            steps {
                // Log in to the Docker registry (e.g., Docker Hub)
                sh 'sudo docker login -u mayurgavli -p Mayur1990$'
            }
        }
        stage('Push to Docker Registry') {
            steps {
                // Push the Docker image to the registry of docker 
                sh 'sudo docker tag test_image:1.0 mayurgavli/mayur_npn:1.6'
                sh 'sudo docker push mayurgavli/mayur_npn:1.6'
                
            }
        }
    }
}

